package POJOFiles;
// Generated Jan 18, 2021 11:09:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Groupchat generated by hbm2java
 */
public class Groupchat  implements java.io.Serializable {


     private Integer idgroupChat;
     private String username;
     private String content;
     private Date cratedTime;
     private int isActive;

    public Groupchat() {
    }

    public Groupchat(String username, String content, Date cratedTime, int isActive) {
       this.username = username;
       this.content = content;
       this.cratedTime = cratedTime;
       this.isActive = isActive;
    }
   
    public Integer getIdgroupChat() {
        return this.idgroupChat;
    }
    
    public void setIdgroupChat(Integer idgroupChat) {
        this.idgroupChat = idgroupChat;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCratedTime() {
        return this.cratedTime;
    }
    
    public void setCratedTime(Date cratedTime) {
        this.cratedTime = cratedTime;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }




}


