package POJOFiles;
// Generated Jan 18, 2021 11:09:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Individualchat generated by hbm2java
 */
public class Individualchat  implements java.io.Serializable {


     private Integer idindividualChat;
     private String senderUname;
     private String receiverUname;
     private String content;
     private Date createdTime;
     private int isActive;

    public Individualchat() {
    }

    public Individualchat(String senderUname, String receiverUname, String content, Date createdTime, int isActive) {
       this.senderUname = senderUname;
       this.receiverUname = receiverUname;
       this.content = content;
       this.createdTime = createdTime;
       this.isActive = isActive;
    }
   
    public Integer getIdindividualChat() {
        return this.idindividualChat;
    }
    
    public void setIdindividualChat(Integer idindividualChat) {
        this.idindividualChat = idindividualChat;
    }
    public String getSenderUname() {
        return this.senderUname;
    }
    
    public void setSenderUname(String senderUname) {
        this.senderUname = senderUname;
    }
    public String getReceiverUname() {
        return this.receiverUname;
    }
    
    public void setReceiverUname(String receiverUname) {
        this.receiverUname = receiverUname;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }




}


